apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  selector:
    app: student-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30036
